UNO\EvaluacionesBundle\Entity\Ccoach:
    type: entity
    table: Ccoach
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id
            generator:
                strategy: NONE
    fields:
        user:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        coordinador:
            type: integer
            nullable: false
            options:
                unsigned: false
        zona:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        img:
            type: string
            nullable: true
            length: 65
            options:
                fixed: false
    lifecycleCallbacks: {  }
