UNO\EvaluacionesBundle\Entity\Option:
    type: entity
    table: Option
    id:
        optionid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: optionId
            generator:
                strategy: IDENTITY
    fields:
        option:
            type: string
            nullable: false
            length: 250
            options:
                fixed: false
    manyToMany:
        questionxsurveySurveySurveyid:
            targetEntity: Questionxsurvey
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: optionOptionid
            joinTable:
                name: optionxquestion
                joinColumns:
                    -
                        name: Option_optionId
                        referencedColumnName: optionId
                inverseJoinColumns:
                    -
                        name: QuestionXSurvey_Survey_surveyId
                        referencedColumnName: Survey_surveyId
                    -
                        name: QuestionXSurvey_Question_questionId
                        referencedColumnName: Question_questionId
            orderBy: null
    lifecycleCallbacks: {  }
