UNO\EvaluacionesBundle\Entity\Personschool:
    type: entity
    table: PersonSchool
    id:
        personid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: personId
            generator:
                strategy: NONE
        schoolid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: schoolId
            generator:
                strategy: NONE
        schoolperiodid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: schoolPeriodId
            generator:
                strategy: NONE
        schoollevelid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: schoolLevelId
            generator:
                strategy: NONE
        profileid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: profileId
            generator:
                strategy: NONE
    fields:{}
    lifecycleCallbacks: {  }
