UNO\EvaluacionesBundle\Entity\Uservalidationemail:
    type: entity
    table: UserValidationEmail
    id:
        iduservalidationemail:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idUserValidationEmail
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        code:
            type: integer
            nullable: false
            options:
                unsigned: false
        dateregister:
            type: datetime
            nullable: false
            column: dateRegister
        data:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        personid:
            type: integer
            nullable: false
            column: personId
            options:
                unsigned: false
    lifecycleCallbacks: {  }
