UNO\EvaluacionesBundle\Entity\Userhttpsession:
    type: entity
    table: UserHttpSession
    id:
        iduserhttpsession:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idUserHttpSession
            generator:
                strategy: IDENTITY
    fields:
        browser:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        browserversion:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
            column: browserVersion
        platform:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        sid:
            type: string
            nullable: false
            length: 65
            options:
                fixed: false
        ipcliente:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: ipCliente
        loggedin:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: loggedIn
        startsession:
            type: datetime
            nullable: false
            column: startSession
        personid:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: personId
    lifecycleCallbacks: {  }
