uno_evaluaciones:
    resource: "@UNOEvaluacionesBundle/Controller/"
    type:     annotation
    prefix:   /
login:
    path:     /
    defaults: { _controller: UNOEvaluacionesBundle:Login\Login:index}
logout:
    path:     /logout
    defaults: { _controller: UNOEvaluacionesBundle:Login\Login:logout}
success:
    path:     /success
    defaults: { _controller: UNOEvaluacionesBundle:Login\Login:success}
inicio:
    path:     /inicio
    defaults: { _controller: UNOEvaluacionesBundle:Evaluaciones\Inicio:index}
autentication:
    path:     /ajax/autentication
    defaults: { _controller: UNOEvaluacionesBundle:Login\Login:autentication }
    methods:  [POST]
forwardMail:
    path:     /forwardMail
    defaults: { _controller: UNOEvaluacionesBundle:Login\Login:forwardMail }
linkCode:
    path:     /linkCode
    defaults: { _controller: UNOEvaluacionesBundle:Login\Alta:linkCode }
responder:
    path:   /responder/{id}
    defaults: {_controller: UNOEvaluacionesBundle:Evaluaciones/Responder:index}
    requirements:
        id: \d+
listar:
    path:   /listar
    defaults: {_controller: UNOEvaluacionesBundle:Evaluaciones/Listar:index}
test:
    path:   /test
    defaults: {_controller: UNOEvaluacionesBundle:Login\Login:test}
resumen:
    path:   /resumen/{surveyId}
    defaults: {_controller: UNOEvaluacionesBundle:Evaluaciones/Resumen:index}
    requirements:
            surveyId: \d+
evaluaciones:
    path:   /evaluaciones
    defaults: {_controller: UNOEvaluacionesBundle:Evaluaciones/Admin:index}
estadisticas:
    path:   /estadisticas
    defaults: {_controller: UNOEvaluacionesBundle:Stats\Stats:index}
ajaxstats:
    path:     /ajax/stats
    defaults: { _controller: UNOEvaluacionesBundle:Stats\AjaxStats:index }
    methods:  [POST]
crear:
    path:   /evaluaciones/crear
    defaults: {_controller: UNOEvaluacionesBundle:Evaluaciones/Crear:index}
save:
    path:   /evaluaciones/crear/save
    defaults: {_controller: UNOEvaluacionesBundle:Evaluaciones/Crear:save}
    methods: [POST]
salvarResp:
    path:   /responder/salvar
    defaults: {_controller: UNOEvaluacionesBundle:Evaluaciones/Responder:guardar}
    methods:  [POST]
ajaxSurveyStatus:
    path:   /evaluaciones/setstatus
    defaults: {_controller: UNOEvaluacionesBundle:Evaluaciones/Admin:setSurveyStatus}
    methods: [POST]

#API Surveys

APISurveys:
    path: /api/v0/surveys
    defaults: {_controller: UNOEvaluacionesBundle:API/APISurvey:survey}
APISurvey:
    path: /api/v0/survey/{surveyid}
    defaults: {_controller: UNOEvaluacionesBundle:API/APISurvey:surveybyid}
    requirements:
            surveyid: \d+
APISurveysSchool:
    path: /api/v0/surveys/school/{schoolid}
    defaults: {_controller: UNOEvaluacionesBundle:API/APISurvey:surveysbyschool}
    requirements:
            schoolid: \d+
APISurveysRole:
    path: /api/v0/surveys/level/{schoollevelid}/profile/{profileid}
    defaults: {_controller: UNOEvaluacionesBundle:API/APISurvey:surveybyrole}
    requirements:
            schoollevelid: \d+
            profileid: \d+
APISurveysLevel:
    path: /api/v0/surveys/level/{schoollevelid}
    defaults: {_controller: UNOEvaluacionesBundle:API/APISurvey:surveybylevel}
    requirements:
            schoollevelid: \d+
APISurveysProfile:
    path: /api/v0/surveys/profile/{profileid}
    defaults: {_controller: UNOEvaluacionesBundle:API/APISurvey:surveybyprofile}
    requirements:
            profileid: \d+
APISurveysPerson:
    path: /api/v0/surveys/person/{personid}
    defaults: {_controller: UNOEvaluacionesBundle:API/APISurvey:surveybyperson}
    requirements:
            personid: \d+

#API Stats - Progress

APIStatsProgress:
    path: /api/v0/stats/progress
    defaults: {_controller: UNOEvaluacionesBundle:API/APIStats:progress}
APIStatsProgressBySchool:
    path: /api/v0/stats/progress/school/{schoolid}
    defaults: {_controller: UNOEvaluacionesBundle:API/APIStats:progressbyschool}
    requirements:
            schoolid: \d+
APIStatsProgressByPerson:
    path: /api/v0/stats/progress/person/{personid}
    defaults: {_controller: UNOEvaluacionesBundle:API/APIStats:progressbyperson}
    requirements:
            personid: \d+
APIStatsProgressByProfile:
    path: /api/v0/stats/progress/profile/{profileid}
    defaults: {_controller: UNOEvaluacionesBundle:API/APIStats:progressbyprofile}
    requirements:
            profileid: \d+
APIStatsProgressByLevel:
    path: /api/v0/stats/progress/level/{levelid}
    defaults: {_controller: UNOEvaluacionesBundle:API/APIStats:progressbylevel}
    requirements:
            levelid: \d+
APIStatsProgressByLevelProfile:
    path: /api/v0/stats/progress/level/{levelid}/profile{profileid}
    defaults: {_controller: UNOEvaluacionesBundle:API/APIStats:progressbyprofile}
    requirements:
            profileid: \d+
            levelid: \d+
APIStatsProgressBySchoolRole:
    path: /api/v0/stats/progress/school/{schoolid}/level/{levelid}/profile/{profileid}
    defaults: {_controller: UNOEvaluacionesBundle:API/APIStats:progressbyschoolrole}
    requirements:
            profileid: \d+
            schoolid: \d+
            levelid: \d+
APIStatsProgressBySchoolLevel:
    path: /api/v0/stats/progress/school/{schoolid}/level/{levelid}
    defaults: {_controller: UNOEvaluacionesBundle:API/APIStats:progressbyschoollevel}
    requirements:
            schoolid: \d+
            levelid: \d+
APIStatsProgressBySchoolProfile:
    path: /api/v0/stats/progress/school/{schoolid}/profile/{profileid}
    defaults: {_controller: UNOEvaluacionesBundle:API/APIStats:progressbyprofile}
    requirements:
            schoolid: \d+
            profileid: \d+

#API Stats - Results

APIStatsResultsAll:
    path: /api/v0/stats/results
    defaults: {_controller: UNOEvaluacionesBundle:API/APIStatsresults:allstats}
APIStatsResultsBySurvey:
    path: /api/v0/stats/results/survey/{surveyid}
    defaults: {_controller: UNOEvaluacionesBundle:API/APIStatsresults:statsbysurvey}
    requirements:
            surveyid: \d+
APIStatsResultsBySchool:
    path: /api/v0/stats/results/school/{schoolid}
    defaults: {_controller: UNOEvaluacionesBundle:API/APIStatsresults:statsbyschool}
    requirements:
            schoolid: \d+
APIStatsResultsByPerson:
    path: /api/v0/stats/results/person/{personid}
    defaults: {_controller: UNOEvaluacionesBundle:API/APIStatsresults:statsbyperson}
    requirements:
                personid: \d+
APIStatsResultsBySchoolLevel:
    path: /api/v0/stats/results/school/{schoolid}/level/{levelid}
    defaults: {_controller: UNOEvaluacionesBundle:API/APIStatsresults:statsbyschoollevel}
    requirements:
                schoolid: \d+
                levelid: \d+
APIStatsResultsBySchoolProfile:
    path: /api/v0/stats/results/school/{schoolid}/profile/{profileid}
    defaults: {_controller: UNOEvaluacionesBundle:API/APIStatsresults:statsbyschoollevel}
    requirements:
                schoolid: \d+
                profileid: \d+
APIStatsResultsBySchoolRole:
    path: /api/v0/stats/results/school/{schoolid}/level/{levelid}/profile/{profileid}
    defaults: {_controller: UNOEvaluacionesBundle:API/APIStatsresults:statsbyschoollevel}
    requirements:
                schoolid: \d+
                levelid: \d+
                profileid: \d+
APIStatsResultsBySurveySchool:
    path: /api/v0/stats/results/survey/{surveyid}/school/{schoolid}
    defaults: {_controller: UNOEvaluacionesBundle:API/APIStatsresults:statsbysurveyschool}
    requirements:
                surveyid: \d+
                schoolid: \d+
APIStatsResultsBySurveyPerson:
    path: /api/v0/stats/results/survey/{surveyid}/person/{personid}
    defaults: {_controller: UNOEvaluacionesBundle:API/APIStatsresults:statsbysurveyperson}
    requirements:
                surveyid: \d+
                personid: \d+
APIResults:
    path: /api/v0/results
    defaults: {_controller: UNOEvaluacionesBundle:API/APIResults:results}
APIResultBySurveyPerson:
  path: /api/v0/result/survey/{surveyId}/person/{personId}
  defaults: {_controller: UNOEvaluacionesBundle:API/APIResults:resultSurveyPerson, personId = null}
  requirements:
              surveyId: \d+
              personId: \d+
MailTest:
  path: /mailing/test
  defaults: {_controller: UNOEvaluacionesBundle:Notifications/Notifications:test}
APINotificationsNewSurveys:
  path: /api/v0/notifications/newsurveys/daysago/{daysago}
  defaults: {_controller: UNOEvaluacionesBundle:API/APINotifications:newsurveys}
  requirements:
              daysago: \d+
