uno_evaluaciones:
    resource: "@UNOEvaluacionesBundle/Controller/"
    type:     annotation
    prefix:   /
login:
    path:     /
    defaults: { _controller: UNOEvaluacionesBundle:Login:index}
responder:
    path:   /responder
    defaults: {_controller: UNOEvaluacionesBundle:Evaluaciones/Responder:index}
listar:
    path:   /listar
    defaults: {_controller: UNOEvaluacionesBundle:Evaluaciones/Listar:index}