uno_evaluaciones:
    resource: "@UNOEvaluacionesBundle/Controller/"
    type:     annotation
    prefix:   /
login:
    path:     /
    defaults: { _controller: UNOEvaluacionesBundle:Login\Login:index}
logout:
    path:     /logout
    defaults: { _controller: UNOEvaluacionesBundle:Login\Login:logout}
success:
    path:     /success
    defaults: { _controller: UNOEvaluacionesBundle:Login\Login:success}
inicio:
    path:     /inicio
    defaults: { _controller: UNOEvaluacionesBundle:Evaluaciones\Inicio:index}
autentication:
    path:     /ajax/autentication
    defaults: { _controller: UNOEvaluacionesBundle:Login\Login:autentication }
    methods:  [POST]
forwardMail:
    path:     /forwardMail
    defaults: { _controller: UNOEvaluacionesBundle:Login\Login:forwardMail }
linkCode:
    path:     /linkCode
    defaults: { _controller: UNOEvaluacionesBundle:Login\Alta:linkCode }
responder:
    path:   /responder/{id}
    defaults: {_controller: UNOEvaluacionesBundle:Evaluaciones/Responder:index}
    requirements:
        id: \d+
listar:
    path:   /listar
    defaults: {_controller: UNOEvaluacionesBundle:Evaluaciones/Listar:index}
test:
    path:   /test
    defaults: {_controller: UNOEvaluacionesBundle:Login\Login:test}
resumen:
    path:   /resumen/{surveyId}
    defaults: {_controller: UNOEvaluacionesBundle:Evaluaciones/Resumen:index}
    requirements:
            surveyId: \d+
evaluaciones:
    path:   /evaluaciones
    defaults: {_controller: UNOEvaluacionesBundle:Evaluaciones/Admin:index}
estadisticas:
    path:   /estadisticas
    defaults: {_controller: UNOEvaluacionesBundle:Stats\Stats:index}
ajaxstats:
    path:     /ajax/stats
    defaults: { _controller: UNOEvaluacionesBundle:Stats\AjaxStats:index }
    methods:  [POST]
crear:
    path:   /evaluaciones/crear
    defaults: {_controller: UNOEvaluacionesBundle:Evaluaciones/Crear:index}
save:
    path:   /evaluaciones/crear/save
    defaults: {_controller: UNOEvaluacionesBundle:Evaluaciones/Crear:save}
    methods: [POST]
salvarResp:
    path:   /responder/salvar
    defaults: {_controller: UNOEvaluacionesBundle:Evaluaciones/Responder:guardar}
    methods:  [POST]